[package]
name = "flamelang-hir"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
flamelang-ast.workspace = true
serde.workspace = true
thiserror.workspace = true
