[package]
name = "flamelang-mir"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
flamelang-hir.workspace = true
serde.workspace = true
thiserror.workspace = true
